version: '3.2'

services:
  iris:
    #image: store/intersystems/iris-ml-community:2020.3.0.304.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tryiris

    ports:
    # 1972 is the superserver default port 
    - "1972:1972"
    # 52773 is the webserver/management portal port
    - "52773:52773"
   
    volumes:
    # Mounts a local directory for passing in files and test scripts
    - ./:/ISC
                                
    environment:
     - TZ=JST-9